<a href="https://colab.research.google.com/github/samduartedev/analysis-taylor-swift-albuns-2024/blob/main/Taylor_Swift.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/taylor_swift_spotify.csv")

In [ ]:
df.head()

,Unnamed: 0,name,album,release_date,track_number,id,uri,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,duration_ms
0,0,Fortnight (feat. Post Malone),THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,2024-04-19,1,6dODwocEuGzHAavXqTbwHv,spotify:track:6dODwocEuGzHAavXqTbwHv,0.5020,0.504,0.386,0.000015,0.0961,-10.976,0.0308,192.004,0.281,82,228965
1,1,The Tortured Poets Department,THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,2024-04-19,2,4PdLaGZubp4lghChqp8erB,spotify:track:4PdLaGZubp4lghChqp8erB,0.0483,0.604,0.428,0.000000,0.1260,-8.441,0.0255,110.259,0.292,79,293048
2,2,My Boy Only Breaks His Favorite Toys,THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,2024-04-19,3,7uGYWMwRy24dm7RUDDhUlD,spotify:track:7uGYWMwRy24dm7RUDDhUlD,0.1370,0.596,0.563,0.000000,0.3020,-7.362,0.0269,97.073,0.481,80,203801
3,3,Down Bad,THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,2024-04-19,4,1kbEbBdEgQdQeLXCJh28pJ,spotify:track:1kbEbBdEgQdQeLXCJh28pJ,0.5600,0.541,0.366,0.000001,0.0946,-10.412,0.0748,159.707,0.168,82,261228
4,4,"So Long, London",THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,2024-04-19,5,7wAkQFShJ27V8362MqevQr,spotify:track:7wAkQFShJ27V8362MqevQr,0.7300,0.423,0.533,0.002640,0.0816,-11.388,0.3220,160.218,0.248,80,262974

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 582 entries, 0 to 581
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        582 non-null    int64
 1   name              582 non-null    object
 2   album             582 non-null    object
 3   release_date      582 non-null    object
 4   track_number      582 non-null    int64
 5   id                582 non-null    object
 6   uri               582 non-null    object
 7   acousticness      582 non-null    float64
 8   danceability      582 non-null    float64
 9   energy            582 non-null    float64
 10  instrumentalness  582 non-null    float64
 11  liveness          582 non-null    float64
 12  loudness          582 non-null    float64
 13  speechiness       582 non-null    float64
 14  tempo             582 non-null    float64
 15  valence           582 non-null    float64
 16  popularity        582 non-null    int64
 17  duration_ms       582 non-null    int64
dtypes: float64(9), int64(4), object(5)
memory usage: 82.0+ KB

In [ ]:
df['release_date']= pd.to_datetime(df['release_date'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 582 entries, 0 to 581
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              582 non-null    object
 1   album             582 non-null    object
 2   release_date      582 non-null    datetime64[ns]
 3   track_number      582 non-null    int64
 4   id                582 non-null    object
 5   uri               582 non-null    object
 6   acousticness      582 non-null    float64
 7   danceability      582 non-null    float64
 8   energy            582 non-null    float64
 9   instrumentalness  582 non-null    float64
 10  liveness          582 non-null    float64
 11  loudness          582 non-null    float64
 12  speechiness       582 non-null    float64
 13  tempo             582 non-null    float64
 14  valence           582 non-null    float64
 15  popularity        582 non-null    int64
 16  duration_ms       582 non-null    int64
dtypes: datetime64[ns](1), float64(9), int64(3), object(4)
memory usage: 77.4+ KB

In [ ]:
df = df.drop("Unnamed: 0", axis=1)

In [ ]:
df.head()

,name,album,release_date,track_number,id,uri,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,duration_ms
0,Fortnight (feat. Post Malone),THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,2024-04-19,1,6dODwocEuGzHAavXqTbwHv,spotify:track:6dODwocEuGzHAavXqTbwHv,0.5020,0.504,0.386,0.000015,0.0961,-10.976,0.0308,192.004,0.281,82,228965
1,The Tortured Poets Department,THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,2024-04-19,2,4PdLaGZubp4lghChqp8erB,spotify:track:4PdLaGZubp4lghChqp8erB,0.0483,0.604,0.428,0.000000,0.1260,-8.441,0.0255,110.259,0.292,79,293048
2,My Boy Only Breaks His Favorite Toys,THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,2024-04-19,3,7uGYWMwRy24dm7RUDDhUlD,spotify:track:7uGYWMwRy24dm7RUDDhUlD,0.1370,0.596,0.563,0.000000,0.3020,-7.362,0.0269,97.073,0.481,80,203801
3,Down Bad,THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,2024-04-19,4,1kbEbBdEgQdQeLXCJh28pJ,spotify:track:1kbEbBdEgQdQeLXCJh28pJ,0.5600,0.541,0.366,0.000001,0.0946,-10.412,0.0748,159.707,0.168,82,261228
4,"So Long, London",THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,2024-04-19,5,7wAkQFShJ27V8362MqevQr,spotify:track:7wAkQFShJ27V8362MqevQr,0.7300,0.423,0.533,0.002640,0.0816,-11.388,0.3220,160.218,0.248,80,262974

In [ ]:
album_popularity = (
    df.groupby('album')['popularity']
    .mean()
    .reset_index()
    .sort_values(by='popularity', ascending=False)
    .reset_index(drop=True)
)
album_popularity.index += 1
print(album_popularity)

                                                album  popularity
1        THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY   78.774194
2                       THE TORTURED POETS DEPARTMENT   77.000000
3                                               Lover   75.944444
4                                          reputation   75.733333
5                                           Midnights   74.153846
6                                            folklore   72.812500
7                             1989 (Taylor's Version)   72.190476
8                        Speak Now (Taylor's Version)   69.454545
9                              Red (Taylor's Version)   67.233333
10                                           evermore   66.400000
11                          folklore (deluxe version)   65.941176
12                        Fearless (Taylor's Version)   65.269231
13                          evermore (deluxe version)   64.235294
14                   1989 (Taylor's Version) [Deluxe]   63.000000
15                            Midnights (3am Edition)   62.850000
16                   Midnights (The Til Dawn Edition)   62.434783
17                      Taylor Swift (Deluxe Edition)   56.666667
18                                               1989   52.692308
19                                          Speak Now   50.714286
20  folklore: the long pond studio sessions (from ...   49.058824
21                                      1989 (Deluxe)   49.000000
22                         Speak Now (Deluxe Package)   48.363636
23                                                Red   45.000000
24                               Red (Deluxe Edition)   44.954545
25                        Fearless (Platinum Edition)   43.157895
26                          Speak Now World Tour Live   41.312500
27              Live From Clear Channel Stripped 2008   32.250000
28                   Fearless (International Version)   32.000000
29     reputation Stadium Tour Surprise Song Playlist   31.586957

In [ ]:
total_music_by_album = (
    df.groupby('album')['name']
    .count()
    .reset_index(name='music_count')
    .sort_values(by='music_count', ascending=False)
)
total_music_by_album.index += 1
print(total_music_by_album)

                                                album  music_count
29     reputation Stadium Tour Surprise Song Playlist           46
27  folklore: the long pond studio sessions (from ...           34
21       THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY           31
15                             Red (Taylor's Version)           30
7                         Fearless (Taylor's Version)           26
12                   Midnights (The Til Dawn Edition)           23
17                         Speak Now (Deluxe Package)           22
14                               Red (Deluxe Edition)           22
18                       Speak Now (Taylor's Version)           22
4                    1989 (Taylor's Version) [Deluxe]           22
3                             1989 (Taylor's Version)           21
11                            Midnights (3am Edition)           20
2                                       1989 (Deluxe)           19
6                         Fearless (Platinum Edition)           19
9                                               Lover           18
26                          folklore (deluxe version)           17
24                          evermore (deluxe version)           17
5                    Fearless (International Version)           16
25                                           folklore           16
19                          Speak Now World Tour Live           16
13                                                Red           16
20                      THE TORTURED POETS DEPARTMENT           16
22                      Taylor Swift (Deluxe Edition)           15
28                                         reputation           15
23                                           evermore           15
16                                          Speak Now           14
1                                                1989           13
10                                          Midnights           13
8               Live From Clear Channel Stripped 2008            8

In [ ]:
top10 = (
    df[['name', 'album', 'popularity']]
    .sort_values(by='popularity', ascending=False)
    .reset_index(drop=True)
    .head(10)
)
top10.index += 1

In [ ]:
top10

                               name                          album  popularity
1                      Cruel Summer                          Lover          93
2     Fortnight (feat. Post Malone)  THE TORTURED POETS DEPARTMENT          91
3   I Can Do It With a Broken Heart  THE TORTURED POETS DEPARTMENT          88
4                             Lover                          Lover          86
5                         Anti-Hero                      Midnights          85
6                    Don’t Blame Me                     reputation          85
7                            august                       folklore          84
8                          cardigan                       folklore          84
9                          Down Bad  THE TORTURED POETS DEPARTMENT          82
10                 ...Ready For It?                     reputation          82

In [ ]:
longest_5_songs = (
    df[['name', 'duration_ms']]
    .sort_values(by='duration_ms', ascending=False)
    .drop_duplicates(subset='name')
    .head(5)
    .reset_index(drop=True)
)

longest_5_songs['duration_min'] = (
    longest_5_songs['duration_ms'] / 60000
).round(2)

longest_5_songs.index += 1

print(longest_5_songs)

                                                name  duration_ms  \
1  All Too Well (10 Minute Version) (Taylor's Ver...       613026
2                       Dear John (Taylor's Version)       405906
3                              Dear John - Live/2011       404680
4                                          Dear John       403933
5                              Enchanted - Live/2011       389213

   duration_min
1         10.22
2          6.77
3          6.74
4          6.73
5          6.49

In [ ]:
print(longest_5_songs)

                                                name  duration_ms  \
1  All Too Well (10 Minute Version) (Taylor's Ver...       613026
2                       Dear John (Taylor's Version)       405906
3                              Dear John - Live/2011       404680
4                                          Dear John       403933
5                              Enchanted - Live/2011       389213

   duration_min
1         10.22
2          6.77
3          6.74
4          6.73
5          6.49

In [ ]:
popular_songs_classification = (
    df.groupby(['name','danceability','energy'])['popularity']
    .mean()
    .reset_index()
    .sort_values(by=['popularity'], ascending=False)
    .reset_index(drop=True)
    .head(10)
)
popular_songs_classification.index +=1

In [ ]:
print(popular_songs_classification)

                               name  danceability  energy  popularity
1                      Cruel Summer         0.552   0.702        93.0
2     Fortnight (feat. Post Malone)         0.504   0.386        86.5
3                             Lover         0.359   0.543        86.0
4                    Don’t Blame Me         0.615   0.534        85.0
5   I Can Do It With a Broken Heart         0.701   0.751        85.0
6                          cardigan         0.613   0.581        84.0
7                            august         0.532   0.623        84.0
8                    So High School         0.366   0.866        82.0
9                    Guilty as Sin?         0.626   0.428        82.0
10                         Down Bad         0.541   0.366        82.0

In [ ]:
album_popularity.to_csv('album_popularity.csv', index=False)
total_music_by_album.to_csv('total_music_by_album.csv', index=False)
top10.to_csv('top10.csv', index=False)
longest_5_songs.to_csv('longest_5_songs.csv', index=False)
popular_songs_classification.to_csv('popular_songs_classification.csv', index=False)

In [ ]:
longest_5_songs.to_csv('longest_5_songs.csv', index=False)